create database CusToMers;
use CusToMers;
create table CUSTOMERS (
ID int,
NAME varchar(255),
AGE INT, ADDRESS varchar(255),
SALARY double);

INSERT INTO CUSTOMERS (ID, NAME,AGE, ADDRESS , SALARY)
values (1, 'Ha Anh',32,'Da Nang',2000.00);
insert into CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
values(2,'Van Ha',25,'Ha Noi',1500.00);
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (3, 'Vu Bang', 23, 'Vinh', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (4, 'Thu Minh', 25, 'Ha Noi', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (5, 'Hai An', 27, 'Ha Noi', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (6, 'Hoang', 22, 'Ha Noi', 4500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (7, 'Binh', 24, 'Ha Noi', 10000.00 );

